/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dashh;

public class App {
    public static void main(String[] args) {
        Pustakawan pstkwn = new Pustakawan();
        
        pstkwn.logIn("14787", "Wibowo");
        pstkwn.inputAnggota("44UG1", "Helmi", "0896666");
        pstkwn.inputAnggota("44UG2", "Iqbal", "0893213");
        pstkwn.inputKoleksi("Tutorial C++", "Ivan", 20);
        pstkwn.inputKoleksi("Tutorial Jawa", "Terenihye", 50);
        pstkwn.cetakListAnggota();
        System.out.println("\n");
        pstkwn.cetakListKoleksi();
    }
}
